### ISSUE TITLE
Problem with device token in ios

### ISSUE THREAD

**Issue by ajinkyamarathe** [appfeel/cordova-push-notifications#2]
I face problem with creating token id in ios build. i used your sample code as it is works for me to create token-id in android but still i didn't get token id on IOS.

I used intel xdk for this. I pass .p12 certificate & other certificates.

This is my total script i put in my index file i try to put as it is code but there us permission problem(While Attaching documents requires write permission to this repository).

This is devicready function - 
            var pushNotification;

```
        function onDeviceReady() {
            $("#app-status-ul").append('<li>deviceready event received</li>');

            /*document.addEventListener("backbutton", function(e)
            {
                $("#app-status-ul").append('<li>backbutton event received</li>');

                if( $("#home").length > 0)
                {
                    // call this to get a new token each time. don't call it to reuse existing token.
                    //pushNotification.unregister(successHandler, errorHandler);
                    e.preventDefault();
                    navigator.app.exitApp();
                }
                else
                {
                    navigator.app.backHistory();
                }
            }, false);*/
```

Here i provided dummy Sender Id-            

```
            try 
            { 
                pushNotification = window.plugins.pushNotification;
         $("#app-status-ul").append('<li>registering ' + device.platform + '</li>');
                if (device.platform == 'android' || device.platform == 'Android' ||
                        device.platform == 'amazon-fireos' ) {
        pushNotification.register(successHandler, errorHandler, {"senderID":"981362976531","ecb":"onNotification"});        // required!
                } else {
                    pushNotification.register(tokenHandler, errorHandler, {"badge":"true","sound":"true","alert":"true","ecb":"onNotificationAPN"});    
                    // required!
                }
            }
            catch(err) 
            { 
                txt="There was an error on this page.\n\n"; 
                txt+="Error description: " + err.message + "\n\n"; 
                alert(txt); 
            } 
        }
```

Here i want - e.reg to send on server i didn’t get regId even i cannot debug my application i copy paste android - switch case as it is-

```
        // handle APNS notifications for iOS
        function onNotificationAPN(e) {
            if (e.alert) {
                 $("#app-status-ul").append('<li>push-notification: ' + e.alert + '</li>');
                 // showing an alert also requires the org.apache.cordova.dialogs plugin
                 navigator.notification.alert(e.alert);
            }

            if (e.sound) {
                // playing a sound also requires the org.apache.cordova.media plugin
                var snd = new Media(e.sound);
                snd.play();
            }

            if (e.badge) {
                pushNotification.setApplicationIconBadgeNumber(successHandler, e.badge);
            }

             switch( e.event )
            {
                case 'registered':
                if ( e.regid.length > 0 )
                {
                    $("#app-status-ul").append('<li>REGISTERED -> REGID:' + e.regid + "</li>");
                        passDeviceId(e.regid);
                    // Your GCM push server needs to know the regID before it can push to this device
                    // here is where you might want to send it the regID for later use.
                    console.log("regID = " + e.regid);
                }
                break;                    


                default:
                    /*$("#app-status-ul").append('<li>EVENT -> Unknown, an event was received and we do not know what it is</li>');*/
                break;
            }
        }
```

Here code for Android which gives me  -  e.regid
Which i have to pass server. Also worked successfully.

```
        // handle GCM notifications for Android
        function onNotification(e) {
           /* $("#app-status-ul").append('<li>EVENT -> RECEIVED:' + e.event + '</li>');*/

            switch( e.event )
            {
                case 'registered':
                if ( e.regid.length > 0 )
                {
                    $("#app-status-ul").append('<li>REGISTERED -> REGID:' + e.regid + "</li>");
                        passDeviceId(e.regid);
                    // Your GCM push server needs to know the regID before it can push to this device
                    // here is where you might want to send it the regID for later use.
                    console.log("regID = " + e.regid);
                }
                break;

                case 'message':
                    // if this flag is set, this notification happened while we were in the foreground.
                    // you might want to play a sound to get the user's attention, throw up a dialog, etc.
                    if (e.foreground)
                    {
                        /*$("#app-status-ul").append('<li>--INLINE NOTIFICATION--' + '</li>');*/

                            // on Android soundname is outside the payload. 
                                // On Amazon FireOS all custom attributes are contained within payload
                                var soundfile = e.soundname || e.payload.sound;
                                // if the notification contains a soundname, play it.
                                // playing a sound also requires the org.apache.cordova.media plugin
                                var my_media = new Media("/android_asset/www/"+ soundfile);
                        my_media.play();
                    }
                    else
                    {   // otherwise we were launched because the user touched a notification in the notification tray.
                        /*if (e.coldstart)
                            $("#app-status-ul").append('<li>--COLDSTART NOTIFICATION--' + '</li>');
                        else
                        $("#app-status-ul").append('<li>--BACKGROUND NOTIFICATION--' + '</li>');*/
                    }

                    /*$("#app-status-ul").append('<li>MESSAGE -> MSG: ' + e.payload.message + '</li>');*/
                    //android only
                    /*$("#app-status-ul").append('<li>MESSAGE -> MSGCNT: ' + e.payload.msgcnt + '</li>');*/
                    //amazon-fireos only
                   /* $("#app-status-ul").append('<li>MESSAGE -> TIMESTAMP: ' + e.payload.timeStamp + '</li>');*/
                break;

                case 'error':
                    /*$("#app-status-ul").append('<li>ERROR -> MSG:' + e.msg + '</li>');*/
                break;

                default:
                    /*$("#app-status-ul").append('<li>EVENT -> Unknown, an event was received and we do not know what it is</li>');*/
                break;
            }
        }

        function tokenHandler (result) {
            /*$("#app-status-ul").append('<li>token: '+ result +'</li>');*/
            // Your iOS push server needs to know the token before it can push to this device
            // here is where you might want to send it the token for later use.
        }

        function successHandler (result) {
           /* $("#app-status-ul").append('<li>success:'+ result +'</li>');*/
        }

        function errorHandler (error) {
           /* $("#app-status-ul").append('<li>error:'+ error +'</li>');*/
        }

        document.addEventListener('deviceready', onDeviceReady, true);
```

Through this function i can send to  

```
     function passDeviceId(deviceid) {
var http = new XMLHttpRequest();
var url = "http://www.example.com/index.php/api/app/register_device/format/json";
var id = '';
if(window.localStorage.getItem("id") != undefined){
    id = window.localStorage.getItem("id");
}
var params = "deviceid=" + deviceid + "&id="+ id;
http.open("POST", url, true);

//Send the proper header information along with the request
http.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
http.setRequestHeader("Content-length", params.length);
http.setRequestHeader("Connection", "close");

http.onreadystatechange = function () { //Call a function when the state changes.
    if (http.readyState == 4 && http.status == 200) {            
        //JSON.parse(http.responseText)[0].dev_id;            
        window.localStorage.setItem("id") = JSON.parse(http.responseText)[0].dev_id;
    }
}
http.send(params);
```

}
         </script>

**Comment by miqmago** [comment]
Could you paste the code as text please? (In image it's very unreadable).

**Comment by ajinkyamarathe** [comment]
This is my total script i put in my index file i try to put as it is code but there us permission problem(While Attaching documents requires write permission to this repository).

This is devicready function - 
            var pushNotification;
            
            function onDeviceReady() {
                $("#app-status-ul").append('<li>deviceready event received</li>');
                
				/*document.addEventListener("backbutton", function(e)
				{
                	$("#app-status-ul").append('<li>backbutton event received</li>');
  					
      				if( $("#home").length > 0)
					{
						// call this to get a new token each time. don't call it to reuse existing token.
						//pushNotification.unregister(successHandler, errorHandler);
						e.preventDefault();
						navigator.app.exitApp();
					}
					else
					{
						navigator.app.backHistory();
					}
				}, false);*/


Here i provided dummy Sender Id-			

				try 
				{ 
                	pushNotification = window.plugins.pushNotification;
		     $("#app-status-ul").append('<li>registering ' + device.platform + '</li>');
                	if (device.platform == 'android' || device.platform == 'Android' ||
                            device.platform == 'amazon-fireos' ) {
			pushNotification.register(successHandler, errorHandler, {"senderID":"981362976531","ecb":"onNotification"});		// required!
					} else {
                    	pushNotification.register(tokenHandler, errorHandler, {"badge":"true","sound":"true","alert":"true","ecb":"onNotificationAPN"});	
                        // required!
                	}
                }
				catch(err) 
				{ 
					txt="There was an error on this page.\n\n"; 
					txt+="Error description: " + err.message + "\n\n"; 
					alert(txt); 
				} 
            }

Here i want - e.reg to send on server i didn’t get regId even i cannot debug my application i copy paste android - switch case as it is-

            // handle APNS notifications for iOS
            function onNotificationAPN(e) {
                if (e.alert) {
                     $("#app-status-ul").append('<li>push-notification: ' + e.alert + '</li>');
                     // showing an alert also requires the org.apache.cordova.dialogs plugin
                     navigator.notification.alert(e.alert);
                }
                    
                if (e.sound) {
                    // playing a sound also requires the org.apache.cordova.media plugin
                    var snd = new Media(e.sound);
                    snd.play();
                }
                
                if (e.badge) {
                    pushNotification.setApplicationIconBadgeNumber(successHandler, e.badge);
                }
                
                 switch( e.event )
                {
                    case 'registered':
					if ( e.regid.length > 0 )
					{
						$("#app-status-ul").append('<li>REGISTERED -> REGID:' + e.regid + "</li>");
                            passDeviceId(e.regid);
						// Your GCM push server needs to know the regID before it can push to this device
						// here is where you might want to send it the regID for later use.
						console.log("regID = " + e.regid);
					}
                    break;                    
                    
                    
                    default:
						/*$("#app-status-ul").append('<li>EVENT -> Unknown, an event was received and we do not know what it is</li>');*/
                    break;
                }
            }


Here code for Android which gives me  -  e.regid
Which i have to pass server. Also worked successfully.
            
            // handle GCM notifications for Android
            function onNotification(e) {
               /* $("#app-status-ul").append('<li>EVENT -> RECEIVED:' + e.event + '</li>');*/
                
                switch( e.event )
                {
                    case 'registered':
					if ( e.regid.length > 0 )
					{
						$("#app-status-ul").append('<li>REGISTERED -> REGID:' + e.regid + "</li>");
                            passDeviceId(e.regid);
						// Your GCM push server needs to know the regID before it can push to this device
						// here is where you might want to send it the regID for later use.
						console.log("regID = " + e.regid);
					}
                    break;
                    
                    case 'message':
                    	// if this flag is set, this notification happened while we were in the foreground.
                    	// you might want to play a sound to get the user's attention, throw up a dialog, etc.
                    	if (e.foreground)
                    	{
							/*$("#app-status-ul").append('<li>--INLINE NOTIFICATION--' + '</li>');*/
						      
						        // on Android soundname is outside the payload. 
					                // On Amazon FireOS all custom attributes are contained within payload
					                var soundfile = e.soundname || e.payload.sound;
					                // if the notification contains a soundname, play it.
					                // playing a sound also requires the org.apache.cordova.media plugin
					                var my_media = new Media("/android_asset/www/"+ soundfile);
							my_media.play();
						}
						else
						{	// otherwise we were launched because the user touched a notification in the notification tray.
							/*if (e.coldstart)
								$("#app-status-ul").append('<li>--COLDSTART NOTIFICATION--' + '</li>');
							else
							$("#app-status-ul").append('<li>--BACKGROUND NOTIFICATION--' + '</li>');*/
						}
							
						/*$("#app-status-ul").append('<li>MESSAGE -> MSG: ' + e.payload.message + '</li>');*/
                        //android only
						/*$("#app-status-ul").append('<li>MESSAGE -> MSGCNT: ' + e.payload.msgcnt + '</li>');*/
                        //amazon-fireos only
                       /* $("#app-status-ul").append('<li>MESSAGE -> TIMESTAMP: ' + e.payload.timeStamp + '</li>');*/
                    break;
                    
                    case 'error':
						/*$("#app-status-ul").append('<li>ERROR -> MSG:' + e.msg + '</li>');*/
                    break;
                    
                    default:
						/*$("#app-status-ul").append('<li>EVENT -> Unknown, an event was received and we do not know what it is</li>');*/
                    break;
                }
            }
            
            function tokenHandler (result) {
                /*$("#app-status-ul").append('<li>token: '+ result +'</li>');*/
                // Your iOS push server needs to know the token before it can push to this device
                // here is where you might want to send it the token for later use.
            }
			
            function successHandler (result) {
               /* $("#app-status-ul").append('<li>success:'+ result +'</li>');*/
            }
            
            function errorHandler (error) {
               /* $("#app-status-ul").append('<li>error:'+ error +'</li>');*/
            }
            
			document.addEventListener('deviceready', onDeviceReady, true);
        
Through this function i can send to  
         
         function passDeviceId(deviceid) {
    var http = new XMLHttpRequest();
    var url = "http://www.example.com/index.php/api/app/register_device/format/json";
    var id = '';
    if(window.localStorage.getItem("id") != undefined){
        id = window.localStorage.getItem("id");
    }
    var params = "deviceid=" + deviceid + "&id="+ id;
    http.open("POST", url, true);

    //Send the proper header information along with the request
    http.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
    http.setRequestHeader("Content-length", params.length);
    http.setRequestHeader("Connection", "close");

    http.onreadystatechange = function () { //Call a function when the state changes.
        if (http.readyState == 4 && http.status == 200) {            
            //JSON.parse(http.responseText)[0].dev_id;            
            window.localStorage.setItem("id") = JSON.parse(http.responseText)[0].dev_id;
        }
    }
    http.send(params);
}
         </script>
