### ISSUE TITLE
Cordova 5.4.1 deprecated type generates 12 warnings

### ISSUE THREAD

**Issue by ShamimIslam** [appfeel/cordova-push-notifications#5]
Love your plugin. Fewest number of issues I've seen reported. It just _works_.

BUT: I am seeing the following 12 times and it will only get worse in Cordova 6.2.0 (next version)

Plugins/cordova-push-notifications/PushPlugin.m:137:61: warning: 'enabledRemoteNotificationTypes' is deprecated: first deprecated in iOS 8.0 - Please use -[UIApplication isRegisteredForRemoteNotifications], or -[UIApplication currentUserNotificationSettings] to retrieve user-enabled remote notification and user notification settings [-Wdeprecated-declarations]
    NSUInteger rntypes = [[UIApplication sharedApplication] enabledRemoteNotificationTypes]

Do not know if this is something you can control or not or what the right type should be.

**Comment by miqmago** [comment]
Well, this plugin is a little unmantained right now, as there is the official one in Phonegap: https://github.com/phonegap/phonegap-plugin-push

**Comment by ShamimIslam** [comment]
Yes and there area 100's of bells and whistles and 191 open issues and 8
pull requests active.

And yet the older one "just works" and would continue to "just work" if we
could get the warnings to go away.

The code has not changed significantly between versions for the parts that
are only in the older one. I looked. So why go with newer code that's buggy
when older code just needs massaging.

If it ain't broke, don't fix it. The latest shiny shiny has a higher
maintenance cost if i have to keep fixing things for different setups.

Are there advantages to the new one that I don't know of? I don't feel like
redoing my entire exposure to the API in my current production app. And the
old one "just worked".

**Comment by miqmago** [comment]
Hmmm... ok thanks, you convinced me :) Will take a look, please, could you help me a little with it? I've been out of this repo too many time to fastly know what should be improved if there is something that does not work.

**Comment by ShamimIslam** [comment]
I'll have to go back through my repo - I started massaging a few different
files - but then I ran out of time due to a deadline.

Now it's become more of an issue because I can't upgrade to XDK 3649 -
they're really pushing me to get out of 5.4.1.

I'll have a look this week and at least name some files for you to look at.

**Comment by miqmago** [comment]
Comming soon, do not despair :)

**Comment by miqmago** [comment]
Right now it works (even there are still some warnings)
Tested in ios 10 :)

**Comment by ShamimIslam** [comment]
Ok - but which version of Cordova are you running on? 5.4.1 works but I'm required to use 5.6 in the next version of the XDK and the one after that bumps me up to 6.x.

Thanks.

**Comment by miqmago** [comment]
cordova cli version: 6.4.0 (latest but does not affect to the plugin)
cordova ios platform version: 4.3.1 (latest one, see https://github.com/apache/cordova-ios/releases)

**Comment by ShamimIslam** [comment]
Ok - I will try it out in the newer XDK with the updated Cordova.
