### ISSUE TITLE
Do i need to upload something to GCM (FCM) InvalidRegistration iOS

### ISSUE THREAD

**Issue by luisfusim** [appfeel/cordova-push-notifications#6]
Im getting InvalidRegistration but the registration return me a registrationID like this;
b4b2147d9a6b7ccbfb47f7a821d3ebf9ac89bf418b11d2d887b174bca77XXXXX
Im not sure if its a valid GCM Token or is a APN ID.

Searching on internet found something to upload p12 files to GCM

**Comment by miqmago** [comment]
Take a look at https://github.com/phonegap/phonegap-plugin-push. This is a really more up to date than this plugin. Thanks!
